name: "Sync to S3"
description: "Sync a directory to a bucket in an S3-compliant Object Storage"
author: Cyso Cloud
runs:
  using: docker
  image: 'docker/Dockerfile'
branding:
  icon: refresh-cw
  color: green
