name: Mirror Staging and Master

on:
  push:
    branches:
      - staging
      - master

jobs:
  mirror:
    runs-on: actions-runners-machete
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add remote to known hosts
        run: |
          ssh-keyscan git.cloud.cyso.dev > ~/.ssh/known_hosts

      - name: Add remote and push
        run: |
          git remote add mirror ssh://git@git.cloud.cyso.dev/cyso-cloud/flux-machete.git
          git fetch mirror
          git push mirror HEAD:${GITHUB_REF##*/} --force

      - name: Remove SSH Key
        run: |
          sudo rm -rf ~/.ssh/
